author: lee vanrell
baseurl: ''
description: 'Software Engineer attempts to write a blog.  Focused on programming,
  3d printing, arduino''s, sdr, and more. '
show_excerpts: true
email: leegvanrell@gmail.com
exclude: [.editorconfig, .git, .jekyll-cache, Gemfile, Gemfile.lock, LICENSE.md, README.md, node_modules]
host: 0.0.0.0
permalink: pretty
markdown: kramdown
plainwhite:
  dark_mode: true
  search: true
  #analytics_id: UA-156487363-1
  date_format: '%b %-d, %Y'
  name: Lee Vanrell
  portfolio_image: "assets/portfolio.png"
  html_lang: "en"
  navigation:
  - {title: About Me, url: /about}
  - {title: Bookmarks, url: /bookmarks}
  - {title: Subscribe, url: /feed.xml}
  show_excerpts: true
  sitemap: true
  condensed_mobile:
  - home
  - post
  - page
  social_links: {github: leevanrell, linkedIn: in/leevanrell, rss: rss, twitter: lee_vanrell}
  tagline: Software Engineer
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
remote_theme: thelehhman/plainwhite-jekyll
sass: {sass_dir: _sass, style: ':compressed'}
scholar: {style: mla}
show_excerpts: true
tagline: software engineering at his worst.
theme: plainwhite
title: Lee Vanrell
url: https://leevanrell.github.io
